### ISSUE TITLE
Webpack support?

### ISSUE THREAD

**Issue by navxio** [tivac/svelte-translator#23]
I have an app written is svelte2, but I want to add new features to it in Svelte3.. For the features currently working, is it possible to use the svelte3 loader with svelte-translator for svelte2 files?

**Comment by tivac** [comment]
I would love to see a PR adding webpack support! I don't personally use webpack so I'm unlikely to write that code soon. I imagine you could get most of the way there by inspecting the history of the official webpack loader and seeing what it looked like before it was switched over to use v3.

**Comment by tivac** [comment]
Probably not an issue any more, it's been a while!
